/* eslint-disable @next/next/no-page-custom-font */
import type { Metadata } from "next";
import { NotoSansTC, NotoSerifTC } from "@/components/fonts";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
      <link rel="stylesheet" href="https://fonts.googleapis.com/css2?display=swap&family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200" />
      </head>
      <body className={NotoSansTC.className}>{children}</body>
    </html>
  );
}
